name: slimsnap
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: ^4.6.6

  flutter:
    sdk: flutter

  image_picker: ^1.0.5
  flutter_image_compress: ^2.1.0
  get_storage: ^2.0.3
  permission_handler: ^11.1.0
  flutter_launcher_icons: ^0.13.1
  share_plus: ^7.2.1

dev_dependencies:
    flutter_lints: ^3.0.1
    flutter_test:
      sdk: flutter
    change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21